# Site settings
title: Masahiro Kanai (金井 仁弘)
description: A personal website.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mkanai.github.io" # the base hostname & protocol for your site
repository: "https://github.com/mkanai/mkanai.github.io"

author:
  name:
    en: Masahiro Kanai
    ja: 金井 仁弘 (Masahiro Kanai)
  description:
    en: PhD student in the Bioinformatics and Integrative Genomics (BIG) PhD Program, Harvard Medical School.
    ja: PhD student in the Bioinformatics and Integrative Genomics (BIG) PhD Program, Harvard Medical School.
  emails: 
   - mkanai [at] g.harvard.edu
   - masahiro.kanai [at] riken.jp
   - cani.m.61st [at] gmail.com
  twitter: CanI_61st
  github: mkanai

# gems: ['jekyll/assets']

# Build settings
markdown: redcarpet
highliter: rouge
exclude: ["Gemfile", "Gemfile.lock", "Rakefile", "README.md", "scripts"]
sass:
    sass_dir: ./css

# redcarpet settings
redcarpet:
  extensions: [tables,autolink,strikethrough,no_intra_emphasis,superscript,highlight,with_toc_data]

# jekyll-scholar settings
scholar:
  bibtex_filters:
    - latex
    
  style: ./_bibliography/custom.csl
  locale: en

  sort_by: none
  order: ascending

  source: ./_bibliography
  bibliography: publications.bib
  bibliography_template: "{{reference}}"
  bibliography_list_attributes:
    reversed:

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
  

